core/urls.py
from django.conf.urls import url
from .views import home_view

urlpatterns = [
    url('', home_view, name="home_view"),
]

customer/urls.py
app_name = "customer"

from django.conf.urls import url
from .views import (
    customer_data,
    search_results,
    loan_data,
    repayment_data,
    process_customers_report,
    process_loans_report,
    process_repayments_report,
    excel_customers_report,
    excel_loans_report,
    excel_repayments_report,
)
from .views import CustomerPDFView, LoanPDFView, RepaymentPDFView

# from .views import CustomersPdf, LoansPdf, RepaymentsPdf

urlpatterns = [
    url(r"^details/", customer_data, name="customer_data"),
    url(r"^searchdetails/", search_results, name="search_results"),
    url(r"^loan_details/", loan_data, name="loan_data"),
    url(r"^repayment_details/", repayment_data, name="repayment_data"),
    url(
        r"^customers_report/",
        process_customers_report,
        name="process_customers_report",
    ),
    url(r"^loans_report/", process_loans_report, name="process_loans_report"),
    url(
        r"^repayments_report/",
        process_repayments_report,
        name="process_repayments_report",
    ),
    url(
        r"^customers_pdf_report/",
        CustomerPDFView.as_view(),
        name="customers_pdf_report",
    ),
    url(r"^loans_pdf_report/", LoanPDFView.as_view(), name="loans_pdf_report"),
    url(
        r"^repayments_pdf_report/",
        RepaymentPDFView.as_view(),
        name="repayments_pdf_report",
    ),
    url(
        r"^customers_excel_report/",
        excel_customers_report,
        name="customers_excel_report",
    ),
    url(
        r"^loans_excel_report/", excel_loans_report, name="loans_excel_report"
    ),
    url(
        r"^repayments_excel_report/",
        excel_repayments_report,
        name="repayments_excel_report",
    ),
]

finance/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^customer/", include("customer.urls")),
    url(r"", include("core.urls")),
]

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


def home_view(request):
    return render(request, "home.html")

core/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <title>Financial Data</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            background-color: navy;
        }

        .center {
            width: 80%;
            height: 80%;
            margin: 5% auto;
        }

        .circle {
            background-color: #eee;
            width: 20%;
            border-radius: 50%;
            height: 0;
            padding-bottom: 20%;
            /*setting height and width to be equal*/
            float: left;
            font: bold 20px Helvetica, Verdana, Tahoma;
            text-align: center;
            position: relative;
            margin-bottom: 9%;
        }

        .circle1,
        .circle2,
        .circle4,
        .circle5 {
            margin-right: 20%;
        }

        .circle .text {
            width: 100%;
            margin: 0 auto;
            display: table-cell;
            vertical-align: middle;
            position: absolute;
            top: 45%;
        }

        .circle a {
            text-decoration: none;
            color: navy;
            text-align: center;
        }
    </style>
</head>

<body>

    <div class="center">
        <div class="circle1 circle ">
            <a class="text" href="{% url 'customer:customer_data' %}">Customer data</a>
        </div>
        <div class="circle2 circle ">
            <a class="text" href="{% url 'customer:loan_data' %}">Loan data</a>
        </div>
        <div class="circle3 circle ">
            <a class="text" href="{% url 'customer:repayment_data' %}">Repayment data</a>
        </div>
        <div class="circle4 circle ">
            <a class="text" href="{% url 'customer:process_customers_report' %}">Generate Customer Report</a>
        </div>
        <div class="circle5 circle ">
            <a class="text" href="{% url 'customer:process_loans_report' %}">Generate Loan Report</a>
        </div>
        <div class="circle6 circle ">
            <a class="text" href="{% url 'customer:process_repayments_report' %}">Generate Repayment Report</a>
        </div>
    </div>

</body>

</html>