core/urls.py
from django.conf.urls import url
from .views import home_view

urlpatterns = [
    url('', home_view, name="home_view"),
]

customer/urls.py
app_name = "customer"

from django.conf.urls import url
from .views import (
    customer_data,
    search_results,
    loan_data,
    repayment_data,
    process_customers_report,
    process_loans_report,
    process_repayments_report,
    excel_customers_report,
    excel_loans_report,
    excel_repayments_report,
)
from .views import CustomerPDFView, LoanPDFView, RepaymentPDFView

# from .views import CustomersPdf, LoansPdf, RepaymentsPdf

urlpatterns = [
    url(r"^details/", customer_data, name="customer_data"),
    url(r"^searchdetails/", search_results, name="search_results"),
    url(r"^loan_details/", loan_data, name="loan_data"),
    url(r"^repayment_details/", repayment_data, name="repayment_data"),
    url(
        r"^customers_report/",
        process_customers_report,
        name="process_customers_report",
    ),
    url(r"^loans_report/", process_loans_report, name="process_loans_report"),
    url(
        r"^repayments_report/",
        process_repayments_report,
        name="process_repayments_report",
    ),
    url(
        r"^customers_pdf_report/",
        CustomerPDFView.as_view(),
        name="customers_pdf_report",
    ),
    url(r"^loans_pdf_report/", LoanPDFView.as_view(), name="loans_pdf_report"),
    url(
        r"^repayments_pdf_report/",
        RepaymentPDFView.as_view(),
        name="repayments_pdf_report",
    ),
    url(
        r"^customers_excel_report/",
        excel_customers_report,
        name="customers_excel_report",
    ),
    url(
        r"^loans_excel_report/", excel_loans_report, name="loans_excel_report"
    ),
    url(
        r"^repayments_excel_report/",
        excel_repayments_report,
        name="repayments_excel_report",
    ),
]

finance/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^customer/", include("customer.urls")),
    url(r"", include("core.urls")),
]

customer/models.py
from django.db import models


class CustomerStations(models.Model):
    station_id = models.CharField(max_length=50, blank=True, null=False, primary_key=True)
    station_name = models.CharField(max_length=110, blank=True, null=True)
    daily_target = models.CharField(max_length=50, blank=True, null=True)
    monthly_target = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "customer_stations"

    def __str__(self):
        return self.station_name


class Loans(models.Model):
    loan_date = models.DateField(blank=True, null=True)
    due_date = models.DateField(blank=True, null=True)
    loan_code = models.BigIntegerField(blank=True, null=True)
    loan_amount = models.BigIntegerField(blank=True, null=True)
    loan_status = models.CharField(max_length=50, blank=True, null=True)
    customer_id = models.CharField(max_length=50, blank=True, null=False, primary_key=True, unique=True)
    customer_station = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "loans"

    def __str__(self):
        return ({} - {}).format(self.customer_id, self.loan_amount)


class LoanStatus(models.Model):
    status_id = models.CharField(max_length=50, blank=True, null=False, primary_key=True)
    loan_status = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "loan_status"

    def __str__(self):
        return self.loan_status

customer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from easy_pdf.views import PDFTemplateView
from django.http import HttpResponse

import mysql.connector
import xlwt

customer_details = []
customers = []
loans = []
repayments = []


def customer_data(request):
    db = mysql.connector.connect(
        host="localhost",
        user="increasecapital",
        password="password",
        database="loan_db",
    )

    cursor = db.cursor()

    if request.method == "GET":
        query = "SELECT lo.`customer_id`, lo.`customer_station`, cs.`station_name`  FROM `loans` AS lo INNER JOIN `customer_stations` AS cs ON lo.`customer_station` = cs.`station_id`;"
        cursor.execute(query)
        customer_data = cursor.fetchall()

        for row in customer_data:
            customer_details.append(row)

        cursor.close()

    db.commit()

    db.close()

    return render(
        request, "customer_data.html", {"customer_details": customer_details}
    )


def search_results(request):
    if request.method == "GET":
        search_results = []
        q = request.GET.get("q", None)
        if q:
            for x in customer_details:
                if q in x:
                    search_results.append(x)

    return render(request, "search.html", {"search_results": search_results})


def loan_data(request):
    db = mysql.connector.connect(
        host="localhost",
        user="increasecapital",
        password="password",
        database="loan_db",
    )

    cursor = db.cursor()
    loan_details = []
    if request.method == "GET":
        loan_query = "SELECT lo.`customer_id`, lo.`loan_date`, lo.`due_date`, lo.`loan_code`, lo.`loan_amount` FROM `loans` AS lo;"
        cursor.execute(loan_query)
        loan_data = cursor.fetchall()
        for row in loan_data:
            loan_details.append(row)

        cursor.close()

    db.commit()

    db.close()

    return render(request, "loan_data.html", {"loan_details": loan_details})


def repayment_data(request):
    db = mysql.connector.connect(
        host="localhost",
        user="increasecapital",
        password="password",
        database="loan_db",
    )

    cursor = db.cursor()
    repayment_details = []
    if request.method == "GET":
        repayment_query = "SELECT lo.`loan_status`, ls.`loan_status`, lo.`customer_id`, lo.`loan_date`, lo.`due_date`, lo.`loan_code`, lo.`loan_amount` FROM `loans` AS lo INNER JOIN `loan_status` AS ls ON lo.`loan_status` = ls.`status_id`;"
        cursor.execute(repayment_query)
        repayment_data = cursor.fetchall()
        for row in repayment_data:
            repayment_details.append(row)

        cursor.close()

    db.commit()

    db.close()

    return render(
        request,
        "repayment_data.html",
        {"repayment_details": repayment_details},
    )


def process_customers_report(request):
    if request.method == "GET":
        rangefrom = request.GET.get("rangefrom", None)
        rangeto = request.GET.get("rangeto", None)
        if rangefrom and rangeto:
            db = mysql.connector.connect(
                host="localhost",
                user="increasecapital",
                password="password",
                database="loan_db",
            )

            cursor = db.cursor()

            query = (
                "SELECT lo.`customer_id`, lo.`customer_station`, cs.`station_name`  FROM `loans` AS lo INNER JOIN `customer_stations` AS cs ON lo.`customer_station` = cs.`station_id` WHERE lo.`loan_date` BETWEEN %s AND %s;",
                (rangefrom, rangeto),
            )
            cursor.execute(*query)
            for row in cursor:
                customers.append(row)

            cursor.close()

            db.commit()

            db.close()

            return render(
                request, "customers_report.html", {"customers": customers}
            )

    return render(request, "process_customers_report.html")


def process_loans_report(request):
    if request.method == "GET":
        rangefrom = request.GET.get("rangefrom", None)
        rangeto = request.GET.get("rangeto", None)
        if rangefrom and rangeto:
            db = mysql.connector.connect(
                host="localhost",
                user="increasecapital",
                password="password",
                database="loan_db",
            )

            cursor = db.cursor()

            loan_query = (
                "SELECT lo.`customer_id`, lo.`loan_date`, lo.`loan_code`, lo.`loan_amount` FROM `loans` AS lo WHERE lo.`loan_date` BETWEEN %s AND %s;",
                (rangefrom, rangeto),
            )
            cursor.execute(*loan_query)
            for row in cursor:
                loans.append(row)

            cursor.close()

            db.commit()

            db.close()

            return render(request, "loans_report.html", {"loans": loans})

    return render(request, "process_loans_report.html")


def process_repayments_report(request):
    if request.method == "GET":
        rangefrom = request.GET.get("rangefrom", None)
        rangeto = request.GET.get("rangeto", None)
        if rangefrom and rangeto:
            db = mysql.connector.connect(
                host="localhost",
                user="increasecapital",
                password="password",
                database="loan_db",
            )

            cursor = db.cursor()

            repayment_query = (
                "SELECT lo.`customer_id`, lo.`due_date`, lo.`loan_code`, ls.`loan_status` FROM `loans` AS lo INNER JOIN `loan_status` AS ls ON lo.`loan_status` = ls.`status_id` WHERE lo.`loan_date` BETWEEN %s AND %s LIMIT %s OFFSET %s;",
                (rangefrom, rangeto, batch_size, offset),
            )

            cursor.execute(*repayment_query)

            for row in cursor:
                repayments.append(row)

            cursor.close()

            db.commit()

            db.close()

            return render(
                request, "repayments_report.html", {"repayments": repayments}
            )

    return render(request, "process_repayments_report.html")


class CustomerPDFView(PDFTemplateView):
    template_name = "customers_report.html"

    def get_context_data(self, **kwargs):
        context = super(CustomerPDFView, self).get_context_data(**kwargs)
        return context


class LoanPDFView(PDFTemplateView):
    template_name = "loans_report.html"

    def get_context_data(self, **kwargs):
        context = super(LoanPDFView, self).get_context_data(**kwargs)
        return context


class RepaymentPDFView(PDFTemplateView):
    template_name = "repayments_report.html"

    def get_context_data(self, **kwargs):
        context = super(RepaymentPDFView, self).get_context_data(**kwargs)
        return context

def excel_customers_report(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'inline; filename="Registered Customers.xls"'

    excel_file = xlwt.Workbook(encoding='utf-8')
    excel_sheet = excel_file.add_sheet('Registered Customers')

    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Customer id', 'Customer station', 'Station name',]

    for col_num in range(len(columns)):
        excel_sheet.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()

    rows = customers
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            excel_sheet.write(row_num, col_num, row[col_num], font_style)


    excel_file.save(response)
    return response

def excel_loans_report(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'inline; filename="Disbursed Loans.xls"'

    excel_file = xlwt.Workbook(encoding='utf-8')
    excel_sheet = excel_file.add_sheet('Disbursed Loans')

    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Customer id', 'Loan date', 'Loan code', 'Loan amount',]

    for col_num in range(len(columns)):
        excel_sheet.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()

    rows = loans
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            excel_sheet.write(row_num, col_num, row[col_num], font_style)


    excel_file.save(response)
    return response

def excel_repayments_report(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'inline; filename="Repayments.xls"'

    excel_file = xlwt.Workbook(encoding='utf-8')
    excel_sheet = excel_file.add_sheet('Repayments')

    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Customer id', 'Due date', 'Loan code', 'Loan status',]

    for col_num in range(len(columns)):
        excel_sheet.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()

    rows = repayments
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            excel_sheet.write(row_num, col_num, row[col_num], font_style)


    excel_file.save(response)
    return response

customer/templates/customer_data.html
<!DOCTYPE html>
<html>

<head>
    <title>Customer Details</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <style>
        body {
            width: 800px;
            margin: 0 auto;
            background-color: #eee;
        }

        a {
            text-decoration: none;
            color: #000;
        }
    </style>
</head>

<body>
    <h2>Customer Demographic Information</h2>

    <form method="get">
        <input name="q" type="text" placeholder="Search...">
        <a href="{% url 'customer:search_results' %}"><button>Search</button></a>
    </form>

    <br>

    <table class="table table-striped table-bordered table-condensed table-hover">


        <tr>
            <th>Customer Id</th>
            <th>Customer Station</th>
            <th>Station Name</th>

        </tr>

        {% for customer in customer_details %}

        <tr>
            <td>{{ customer.0 }}</td>
            <td>{{ customer.1 }}</td>
            <td>{{ customer.2 }}</td>

        </tr>

        {% endfor %}

    </table>

</body>

</html>

customer/templates/customers_report.html
<!DOCTYPE html>
<html>

<head>
    <title>Customers Registered</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/css/tableexport.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://fastcdn.org/FileSaver.js/1.1.20151003/FileSaver.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/js/tableexport.min.js"></script>


    <style>
        body {
            width: 800px;
            margin: 0 auto;
            background-color: #eee;
        }

        a {
            text-decoration: none;
            color: #000;
        }
    </style>
</head>

<body>
    <h2><b>Customers Registered Report</b></h2>

    <table class="table table-striped table-bordered table-condensed table-hover">


        <tr>
            <th>Customer Id</th>
            <th>Customer Station</th>
            <th>Station Name</th>

        </tr>

        {% for customer in customers %}

        <tr>
            <td>{{ customer.0 }}</td>
            <td>{{ customer.1 }}</td>
            <td>{{ customer.2 }}</td>

        </tr>

        {% endfor %}

    </table>
    <a href="{% url 'customer:customers_pdf_report' %}"><button>Export to pdf</button></a>
    <a href="{% url 'customer:customers_excel_report' %}"><button>Export to excel</button></a>

</body>

</html>

customer/templates/loan_data.html
<!DOCTYPE html>
<html>

<head>
    <title>Disbursed Loan Details</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <style>
        body {
            width: 800px;
            margin: 0 auto;
            background-color: #eee;
        }
    </style>
</head>

<body>
    <h2>Disbursed Loans Information</h2>

    <table class="table table-striped table-bordered table-condensed table-hover">


        <tr>
            <th>Customer Id</th>
            <th>Loan Date</th>
            <th>Due Date</th>
            <th>Loan Code</th>
            <th>Loan Amount</th>

        </tr>

        {% for loan in loan_details %}

        <tr>
            <td>{{ loan.0 }}</td>
            <td>{{ loan.1 }}</td>
            <td>{{ loan.2 }}</td>
            <td>{{ loan.3 }}</td>
            <td>{{ loan.4 }}</td>

        </tr>

        {% endfor %}

    </table>

</body>

</html>

customer/templates/loans_report.html
<!DOCTYPE html>
<html>

<head>
    <title>Loans Disbursed</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/css/tableexport.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://fastcdn.org/FileSaver.js/1.1.20151003/FileSaver.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/js/tableexport.min.js"></script>

    <style>
        body {
            width: 800px;
            margin: 0 auto;
            background-color: #eee;
        }

        a {
            text-decoration: none;
            color: #000;
        }
    </style>
</head>

<body>
    <h2>Loans Disbursed Report</h2>

    <table class="table table-striped table-bordered table-condensed table-hover">


        <tr>
            <th>Customer Id</th>
            <th>Loan Date</th>
            <th>Loan Code</th>
            <th>Loan Amount</th>

        </tr>

        {% for loan in loans %}

        <tr>
            <td>{{ loan.0 }}</td>
            <td>{{ loan.1 }}</td>
            <td>{{ loan.2 }}</td>
            <td>{{ loan.3 }}</td>

        </tr>

        {% endfor %}

    </table>

    </table>
    <a href="{% url 'customer:loans_pdf_report' %}"><button>Export to pdf</button></a>
    <a href="{% url 'customer:loans_excel_report' %}"><button>Export to excel</button></a>

</body>

</html>

customer/templates/process_customers_report.html
<!DOCTYPE html>
<html>

<head>
    <title>Customers Registered</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/css/tableexport.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://fastcdn.org/FileSaver.js/1.1.20151003/FileSaver.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/js/tableexport.min.js"></script>


    <style>
        body {
            width: 800px;
            margin: 0 auto;
            background-color: navy;
        }

        html,
        body {
            height: 100%;
        }

        .main {
            height: 70%;
            width: 100%;
            display: table;
        }

        .wrapper {
            display: table-cell;
            vertical-align: middle;
        }

        h4,
        label {
            color: #eee;
        }

        a {
            text-decoration: none;
            color: navy;
            font-weight: bold;
        }
    </style>
</head>

<body>
    <div class="main">
        <div class="wrapper">
            <h4><b>Process Customers Registered Report</b></h4>

            <form method="get">
                <label>Select date range for the report between January 2017 and January 2018</label><br><br>
                <input name="rangefrom" type="date" data-date-inline-picker="true"><br><br>
                <input name="rangeto" type="date" data-date-inline-picker="true"><br><br>
                <a href="{% url 'customer:process_customers_report' %}"><button>Generate report</button></a>
            </form>

        </div>
    </div>

</body>

</html>

customer/templates/process_loans_report.html
<!DOCTYPE html>
<html>

<head>
    <title>Loans Disbursed</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/css/tableexport.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://fastcdn.org/FileSaver.js/1.1.20151003/FileSaver.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/js/tableexport.min.js"></script>


    <style>
        body {
            width: 800px;
            margin: 0 auto;
            background-color: navy;
        }

        html,
        body {
            height: 100%;
        }

        .main {
            height: 70%;
            width: 100%;
            display: table;
        }

        .wrapper {
            display: table-cell;
            vertical-align: middle;
        }

        h4,
        label {
            color: #eee;
        }

        a {
            text-decoration: none;
            color: navy;
            font-weight: bold;
        }
    </style>
</head>

<body>

    <div class="main">
        <div class="wrapper">
            <h4><b>Process Loans Disbursed Report</b></h4>

            <form method="get">
                <label>Select date range for the report between January 2017 and January 2018</label><br><br>
                <input name="rangefrom" type="date" data-date-inline-picker="true"><br><br>
                <input name="rangeto" type="date" data-date-inline-picker="true"><br><br>
                <a href="{% url 'customer:process_loans_report' %}"><button>Generate report</button></a>
            </form>

        </div>
    </div>



</body>

</html>

customer/templates/process_repayments_report.html
<!DOCTYPE html>
<html>

<head>
    <title>Loan Repayment</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/css/tableexport.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://fastcdn.org/FileSaver.js/1.1.20151003/FileSaver.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/js/tableexport.min.js"></script>


    <style>
        body {
            width: 800px;
            margin: 0 auto;
            background-color: navy;
        }

        html,
        body {
            height: 100%;
        }

        .main {
            height: 70%;
            width: 100%;
            display: table;
        }

        .wrapper {
            display: table-cell;
            vertical-align: middle;
        }

        h4,
        label {
            color: #eee;
        }

        a {
            text-decoration: none;
            color: navy;
            font-weight: bold;
        }
    </style>
</head>

<body>

    <div class="main">
        <div class="wrapper">
            <h4><b>Process Loan Repayment Report</b></h4>

            <form method="get">
                <label>Select date range for the report between January 2017 and January 2018</label><br><br>
                <input name="rangefrom" type="date" data-date-inline-picker="true"><br><br>
                <input name="rangeto" type="date" data-date-inline-picker="true"><br><br>
                <a href="{% url 'customer:process_repayments_report' %}"><button>Generate report</button></a>
            </form>

        </div>
    </div>

</body>

</html>

customer/templates/repayments_report.html
<!DOCTYPE html>
<html>

<head>
    <title>Loan Repayment Report</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/css/tableexport.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://fastcdn.org/FileSaver.js/1.1.20151003/FileSaver.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/js/tableexport.min.js"></script>

    <style>
        body {
            width: 800px;
            margin: 0 auto;
            background-color: #eee;
        }

        a {
            text-decoration: none;
            color: #000;
        }
    </style>
</head>

<body>
    <h2>Loan Repayment Report</h2>

    <table class="table table-striped table-bordered table-condensed table-hover">


        <tr>
            <th>Customer Id</th>
            <th>Repayment Date</th>
            <th>Loan Code</th>
            <th>Repayment Status</th>

        </tr>

        {% for repayment in repayments %}

        <tr>
            <td>{{ repayment.0 }}</td>
            <td>{{ repayment.1 }}</td>
            <td>{{ repayment.2 }}</td>
            <td>{{ repayment.3 }}</td>

        </tr>

        {% endfor %}

    </table>

    </table>
    <a href="{% url 'customer:repayments_pdf_report' %}"><button>Export to pdf</button></a>
    <a href="{% url 'customer:repayments_excel_report' %}"><button>Export to excel</button></a>


</body>

</html>